# Generated by Django 2.0 on 2020-04-28 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=64)),
                ('destino', models.CharField(max_length=64)),
                ('duracao', models.IntegerField()),
            ],
        ),
    ]
