# Generated by Django 2.0 on 2020-04-28 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroporto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('cidade', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='voo',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aterrizagem', to='voos.Aeroporto'),
        ),
        migrations.AlterField(
            model_name='voo',
            name='origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decolagem', to='voos.Aeroporto'),
        ),
    ]
