# Generated by Django 3.0.5 on 2020-04-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0002_auto_20200427_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passageiros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnome', models.CharField(max_length=64)),
                ('unome', models.CharField(max_length=64)),
                ('voos', models.ManyToManyField(blank=True, related_name='passageiros', to='voos.Voo')),
            ],
        ),
    ]
